project:
  name: CondorView
  description: |
    Proyecto basado en deep learning para el análisis de imágenes satelitales
    orientado a la detección temprana de eventos como inundaciones, incendios,
    deslizamientos, etc., a partir de imagenes provenientes de múltiples satélites.

data:
  raw_data_path: data/raw
  processed_data_path: data/processed
  image_type: RGB           # Se puede cambiar a multispectral, infrarrojo, etc.
  resolution: 64            # Resolución a la que se redimensionarán las imágenes
  satellite_source: Satellogic
  validation_split: 0.2
  batch_size: 32
  image_format: jpg         # Puede ser png, tif, etc.

model:
  architecture: cnn_v1      # Podés cambiar el nombre según la arquitectura
  input_shape: [64, 64, 3]
  num_classes: 5            # Se actualizará automáticamente luego del preprocesamiento
  save_path: models/condorview_model.keras
  load_if_exists: true

training:
  epochs: 15
  optimizer: adam
  loss_function: categorical_crossentropy
  metrics: [accuracy]

prediction:
  threshold: 0.5
  visualize: true

logging:
  log_path: logs/
  log_level: INFO

